# 配置参数详解: https://www.cnblogs.com/cymiao/p/8432681.html
# https://www.cnblogs.com/yaowen/p/8881310.html
spring:
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://192.168.101.17:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 3000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 3000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      filters: stat

